version: '3'

services:
  postgres:
    image: postgres:13
    container_name: bankcard-postgres
    environment:
      POSTGRES_DB: ManagementBankCard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "4321:4321"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bankcard-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ManagementBankCard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      postgres:
        condition:  service_healthy
    volumes:
      - .:/app
      - ~/.m2:/root/.m2

volumes:
  postgres_data:
